#! /usr/bin/env bash

sudo apt install python3-ipython python3-scipy python3-dateutil python3-h5py python3-debian python3-dev python3-dicttoxml python3-flask python3-jupyter-core python3-jupyter-client python3-pandas python3-picamera python3-pika python3-pip python3-pykka python3-redis python3-serial python3-simpy3 python3-skimage python3-sklearn python3-sqlalchemy python3-twisted python3-zmq python3-zmq-dbg
